version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: dnshealthcheckly
    ports:
      - "5432:5432"