version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: dnshealthcheckly
    ports:
      - "5432:5432"