version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8081
    depends_on:
      - backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: dnshealthcheckly
    ports:
      - "5432:5432"
